title: Nisha Ramasubramonian
logo: data assets/Portfolio.jpeg
description: Analyst with a focus in Business Strategy and Project Management
description: San Francisco-Bay Area (open to relocation)
#show_downloads: true
theme: jekyll-theme-minimal
