title: Nisha Ramasubramonian
logo: data assets/Portfolio.jpeg
description: >
  Analyst with a focus in Business Strategy and Project Management
  
  LinkedIn: [https://www.linkedin.com/in/nisharams/](https://www.linkedin.com/in/nisharams/)
  
  Email: nisharamasubramonian@gmail.com
  
  Phone: 925-384-9854
#show_downloads: true
theme: jekyll-theme-minimal
