#title: Nisha Ramasubramonian
#logo: /assets/img/headshot_circle.png
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal

title: Nisha Ramasubramonian
logo: /Users/nisharams/Desktop/Data Portfolio/images/Portfolio.jpeg
description: Analyst with a focus in Business Strategy and Project Management
#show_downloads: false
theme: jekyll-theme-minimal

# Social media links
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/nisharams/
    icon: fab fa-linkedin
  - name: Mail
    url: mailto:nisharamasubramonian@gmail.com
    icon: fas fa-envelope
  - name: Phone
    url: #
    icon: fas fa-phone
    hover_text: (925)384-9854
