title: Nisha Ramasubramonian
logo: /assets/img/headshot_circle.png
description: Analyst with a focus in Business Strategy and Project Management
linkedin: https://www.linkedin.com/in/nisharams/
email: nisharamasubramonian@gmail.com
phone: 925-384-9854
#show_downloads: true
theme: jekyll-theme-minimal
