#title: Nisha Ramasubramonian
#logo: /assets/img/headshot_circle.png
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal

title: Nisha Ramasubramonian
logo: /Users/nisharams/Desktop/Data Portfolio/images/Portfolio.jpeg
description: Analyst with a focus in Business Strategy and Project Management
#show_downloads: false
theme: jekyll-theme-minimal

# Social links
social:
  linkedin: https://www.linkedin.com/in/nisharams/
  mail: mailto:nisharamasubramonian@gmail.com

# Contact information
contact:
  phone: "(925) 384-9854"
