## Education

- M.S., Business Analytics, Supply Chain Operations Analytics | Cornell University (August 2023)
- B.S., Business Administration, Business Analytics | Saint Mary’s College of California (May 2020)
- B.S., Accounting | Saint Mary’s College of California (May 2020)

## Work Experience

Andersen LLC
**Tax Associate II- Private Client Services | Aug 2020- Aug 2022**
**Tax Intern – Private Client Services | Jun 2019-Sep 2019**

- Managed the tax aspects of a portfolio of high-income individuals with complex estate plans (15+ entities) including tax return preparation and forecasting of quarterly tax payments for business planning under tight deadlines.
- Mentored four interns (three received return offers).
- Assisted the National Tax Director on a tax law research project.
- Chosen as an Intern to collaborate directly with the Director of US National Tax on a new tax research project.
- Selected as Intern Team Lead for National InternConnect, responsible for overseeing a team of 6 interns, ensuring seamless coordination and organization, attendee management, and logistical arrangements.

Doris Forman CPA
**Tax Associate II- Private Client Services | Feb 2019- Mar 2020**

- Successfully managed a high volume of tax-related tasks during two busy tax seasons, demonstrating strong time management, organizational, and prioritization skills.
- Collaborated with team members to enhance efficiency and continued learning.

## Skills
## Leadership Experience:
## Extracurriculars:
## Interests and Hobbies
## Certifications
